config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "app_specific_registration/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  mount Attachinary::Engine => "/attachinary"

  get '/payments/create_stripe_payment', to: 'payments#create_stripe_payment'

  scope do
    resources :ceramiques, path: ENV['MODEL'], only: [:create, :index, :destroy, :show, :update]
  end

  resources :orders, only: [:show, :create, :destroy] do
    resources :payments, only: [:new, :create]
  end

  resources :lessons, only: [:new, :create, :destroy, :show]

  resources :users, only: [:update, :create]

  resources :articles, only: [:new, :index, :show, :update, :create, :destroy, :edit]

  #Stages
  get '/stage_confirmation', to: 'lessons#stage_confirmation'
  get '/stage_payment_confirmation', to: 'lessons#stage_payment_confirmation'

  #Pages
  get '/confirmation', to: 'pages#confirmation'
  get '/agenda', to: 'pages#agenda'
  get '/professionnels', to: 'pages#professionnels'
  get '/presse', to: 'pages#presse'
  get '/sites_partenaires', to: 'pages#sites_partenaires'
  get '/cgv', to: 'pages#cgv'
  get '/atelier', to: 'pages#atelier'
  get '/morta', to: 'pages#morta'
  get '/la_briere', to: 'pages#la_briere'
  get '/temoignages', to: 'pages#temoignages'
  get '/sur_mesure', to: 'pages#sur_mesure'
  get '/contact', to: 'pages#contact'
  get '/cgv', to: 'pages#cgv'
  get '/legal', to: 'pages#legal'
  get '/google906057532e2dbb7e', to: 'pages#google906057532e2dbb7e'
  get '/robots.txt', to: 'pages#robots', :defaults => { :format => 'txt' }

  #Sitemap
  get 'sitemap.xml', :to => 'sitemap#sitemap', :defaults => { :format => 'xml' }

  #Subscribe
  post '/user-subscribe', to: "users#subscribe"

  #Root
  root to: 'pages#home'

  #Errors
  get "/404", to: "errors#error_404"

  #API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :shipping_categories, only: [:show]
      resources :promos, only: [:show]
    end
  end

  #Position management through JS
  get '/ceramiques/update_positions_after_swap_in_admin', to: "ceramiques#update_positions_after_swap_in_admin"

end

app/models/order.rb
class Order < ApplicationRecord
  monetize :amount_cents
  monetize :port_cents
  has_many :basketlines
  belongs_to :promo, required: false
  belongs_to :user, required: false
  belongs_to :lesson, required: false

  validates_inclusion_of :take_away, in: [true, false]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  skip_before_action :authenticate_user!, only: [:create, :show, :destroy]

  def create
    @ceramique = Ceramique.find(params[:ceramique].to_i)
    if session[:order].present?
      if Order.find(session[:order].to_i).state != "lost" && Order.find(session[:order].to_i).state != "paid"
        @order = Order.find(session[:order])
        @order.update(state: "pending")
      else
        @order = create_order
      end
    else
      @order = create_order
    end
    if params[:quantity].to_i <= @ceramique.stock
      @basketline = Basketline.create(ceramique: @ceramique, quantity: params[:quantity].to_i, order: @order, with_support: params[:support] == "on")
      @ceramique.update(stock: @ceramique.stock - @basketline.quantity)
      costs = Amountcalculation.new(@order).calculate_amount(@order, current_user)
      @order.update(amount: costs[:total], port: costs[:port], ceramique: collect_ceramiques_for_stats, weight: costs[:weight])
      flash[:notice] = t(:basket_duration, duration: "#{(ENV['BASKETDURATION'].to_f * 60).to_i }")
      redirect_to order_path(@order)
    else
      flash[:alert] = t(:stock_limit, stock: "#{@ceramique.stock}")
      redirect_to ceramique_path(@ceramique)
    end
  end

  def show
    if Order.find(params[:id])
      @order = Order.find(params[:id])
      if @order.state == "pending" || @order.state == "payment page"
        if (current_user || @order.user.present?) && !@order.lesson.present?
          known_user = current_user || @order.user
          costs = Amountcalculation.new(@order).calculate_amount(@order, known_user)
          @order.update(amount: costs[:total], port: costs[:port], weight: costs[:weight], user: known_user)
        end
        @amount = @order.amount
        @port = @order.port
        @weight = @order.weight
        render "show_#{@active_theme.name}"
      else
        flash[:notice] = t(:expired_basket)
        redirect_to ceramiques_path
      end
    else
      flash[:notice] = t(:expired_basket)
      redirect_to ceramiques_path
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @basketline = Basketline.find(params[:basketline_id])
    @ceramique = @basketline.ceramique
    @ceramique.update(stock: @ceramique.stock + @basketline.quantity)
    @basketline.destroy
    costs = Amountcalculation.new(@order).calculate_amount(@order, current_user)
    @order.update(amount: costs[:total], port: costs[:port], weight: costs[:weight], ceramique: @order.ceramique.sub(@ceramique.name+",",""))
    if @order.basketlines.present?
      redirect_to order_path(@order)
    else
      @order.update(state: "lost")
      session[:order] = nil
      redirect_to ceramiques_path
    end
  end

  private

  def create_order
    order  = Order.new(ceramique: @ceramique.name, state: 'pending', take_away: false)
    order.save
    session[:order] = order.id
    return order
  end

  def collect_ceramiques_for_stats
    if @order.basketlines.size == 1
      "#{@ceramique.name}"
    else
      "#{@order.ceramique},#{@ceramique.name}"
    end
  end

end

app/views/admin/orders/_order_stats.html.erb
<div class="top-bloc">

  <%= periodic_stat(30)%>

  <%= periodic_stat(180)%>

</div>

app/views/admin/orders/_pdf_link.html.erb
<p><%= link_to "Facture PDF", admin_order_path(@order, :format => 'pdf') %></p>

app/views/admin/orders/_stat_template.html.erb
<div class="left-right-stat">
  <h2>Ventes sur <%= @text_duration %></h2>
  <div class="month-stat">
    <div class="high-level-stat">
      <% @duration == 30 ? local_orders = @last_month_orders : local_orders = @last_six_month_orders %>
      <% @duration == 30 ? local_hash_category = @categories_sales_data_one : local_hash_category = @categories_sales_data_six %>
      <h3> Nombre de ventes : <%= local_orders %></h3>
      <h3> Chiffre d'affaire : <%= local_hash_category.map{|k, v| v[:"sum"]}.inject(0) {|sum, n| sum + n} %> €</h3>
    </div>
    <h3 class="display-one-month">Ventes par catégories (<a href="#">afficher les produits)</a> : </h3>
    <div class="detailed-stat">

      <% local_hash_category.each do |k, hash_value|%>
        <% if  hash_value[:"sum"] > 0 %>
          <div class="col-xs-50">
            <p class="CA"><%= Category.find(k.to_s.to_i).name.capitalize %> : <%= hash_value[:"sum"] %> €</p>
            <% hash_value.each do |ceramique_id, ceramique_data|%>
              <% if Ceramique.find_by_id(ceramique_id.to_s.to_i)%>
                <% if ceramique_data[:"ceramique_sum"] > 0 %>
                  <p class="inner-CA">ID <%= ceramique_data[:"ceramique_id"]%> - <%= ceramique_data[:"ceramique_name"]%> : <%= ceramique_data[:"ceramique_sum"]%> €</p>
                <% end %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/orders/show.pdf.erb
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<h1>Facture pour commande sur site Eden Black</h1>
<hr>
<h3><%="#{ENV['FIRSTNAME'].capitalize} #{ENV['LASTNAME'].capitalize}"%></h3>
<h3>Tel : <%= ENV['TELEPHONE']%></h3>
<h3>Adresse : <%= ENV['ADDRESS'].gsub("+"," ")%></h3>
<h3>SIRET :  </h3>
<br>
<h2>Client : <%= resource.user.first_name%> <%= resource.user.last_name%></h2>
<h3>Adresse : <%= "#{resource.user.adress} #{resource.user.zip_code} - #{resource.user.city}"%></h3>
<h3>Email : <%= "#{resource.user.email}"%></h3>
<br>
<h2>Contenu de la commande</h2>

   <table style="width: 100%; text-align: center">
      <tr>
        <th>Référence produit</th>
        <th>Quantité</th>
        <th>Prix HT</th>
        <th>TVA <%= ENV['TVA'].to_f * 100 %> %</th>
        <th>Prix TTC</th>
      </tr>
      <% resource.basketlines.each do |basketline| %>
      <tr>
        <td><%= basketline.ceramique_name.capitalize %>. ID: <%= basketline.ceramique_id_on_order %></td>
        <td><%= basketline.ceramique_qty %></td>
        <td><%= humanized_money(basketline.basketline_price * (1 - ENV['TVA'].to_f)) %> €</td>
        <td><%= humanized_money(basketline.basketline_price * ENV['TVA'].to_f) %> €</td>
        <td><%= humanized_money(basketline.basketline_price)%> €</td>
      </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td><strong>Total HT : </strong><%= humanized_money(resource.amount * (1 - ENV['TVA'].to_f))  %> €</td>
        <td><strong>Total TVA : </strong><%= humanized_money(resource.amount * ENV['TVA'].to_f) %> €</td>
        <td></td>
      </tr>
    </table>

<% if ISO3166::Country.find_country_by_alpha2(resource.user.country).subregion.include? "urope" %>
  <p>TVA non applicable (article 293 B du CGI)</p>
<% else %>
  <p>Exonération de TVA art 262-I du code général des impots"</p>
<% end %>

<% if resource.take_away %>
<p> La commande est à retirer en magasin, pas de frais de port.</p>
<p><strong>Total TTC :</strong> <%= humanized_money(resource.amount) %> €</p>
<% else %>
<p>Frais de port: <%= humanized_money(resource.port) %> €</p>
<p><strong>Total TTC :</strong> <%= humanized_money(resource.amount + resource.port) %> €</p>
<% end %>

<h3>Facture règlée le <%= resource.updated_at.strftime("%d/%m/%Y") %> par carte bancaire, sur le site <%= ENV['APPNAME'] %>.</h3>
<h3>Référence de la facture : <%= resource.id%></h3>