config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "app_specific_registration/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  mount Attachinary::Engine => "/attachinary"

  get '/payments/create_stripe_payment', to: 'payments#create_stripe_payment'

  scope do
    resources :ceramiques, path: ENV['MODEL'], only: [:create, :index, :destroy, :show, :update]
  end

  resources :orders, only: [:show, :create, :destroy] do
    resources :payments, only: [:new, :create]
  end

  resources :lessons, only: [:new, :create, :destroy, :show]

  resources :users, only: [:update, :create]

  resources :articles, only: [:new, :index, :show, :update, :create, :destroy, :edit]

  #Stages
  get '/stage_confirmation', to: 'lessons#stage_confirmation'
  get '/stage_payment_confirmation', to: 'lessons#stage_payment_confirmation'

  #Pages
  get '/confirmation', to: 'pages#confirmation'
  get '/agenda', to: 'pages#agenda'
  get '/professionnels', to: 'pages#professionnels'
  get '/presse', to: 'pages#presse'
  get '/sites_partenaires', to: 'pages#sites_partenaires'
  get '/cgv', to: 'pages#cgv'
  get '/atelier', to: 'pages#atelier'
  get '/morta', to: 'pages#morta'
  get '/la_briere', to: 'pages#la_briere'
  get '/temoignages', to: 'pages#temoignages'
  get '/sur_mesure', to: 'pages#sur_mesure'
  get '/contact', to: 'pages#contact'
  get '/cgv', to: 'pages#cgv'
  get '/legal', to: 'pages#legal'
  get '/google906057532e2dbb7e', to: 'pages#google906057532e2dbb7e'
  get '/robots.txt', to: 'pages#robots', :defaults => { :format => 'txt' }

  #Sitemap
  get 'sitemap.xml', :to => 'sitemap#sitemap', :defaults => { :format => 'xml' }

  #Subscribe
  post '/user-subscribe', to: "users#subscribe"

  #Root
  root to: 'pages#home'

  #Errors
  get "/404", to: "errors#error_404"

  #API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :shipping_categories, only: [:show]
      resources :promos, only: [:show]
    end
  end

  #Position management through JS
  get '/ceramiques/update_positions_after_swap_in_admin', to: "ceramiques#update_positions_after_swap_in_admin"

end

app/views/shared/_article_display_quill.html.erb
<% article_typing_quill(article_name) %>
<% if user_signed_in? && current_user.admin && !display_only %>
  <form class="text-editor-form <%= additional_class ?  additional_class : ""%>" block-ref="<%= id%>">
    <input id="quill-name-<%=id%>" name="<%= @article.name %>" type="hidden">
    <input id= "quill-article-id-<%=id%>" article_id="<%= @article.id %>" type="hidden">
    <input id= "quill-user-id-<%=id%>" user_id="<%= current_user.id %>" type="hidden">
    <input id= "quill-locale-<%=id%>" locale="<%= I18n.locale %>" type="hidden">
    <div id="quill-editor-<%= id%>">
        <div id="toolbar-<%= id%>"></div>
        <%= (@article.content || "" ).html_safe %>
      </div>
    <button class="btn btn-primary" type="submit">Enregistrer le contenu</button>
  </form>
<% else %>
  <%= (@article.content || "" ).html_safe %>
<% end %>

app/views/shared/_atelier_pics.html.erb
<% @atelier1 = image_tag ENV['ATELIER1'], class: "img-avatar", alt: "Atelier de Philippe Nerriere pour le travail du Morta." %>
<% @atelier1_path = image_path ENV['ATELIER1'], class: "img-avatar", alt: "Atelier de Philippe Nerriere pour le travail du Morta." %>
<% @atelier2 = image_tag ENV['ATELIER2'], class: "img-city", alt: "Philippe Nerriere réalise toutes les pièces en morta dans son atelier à Guérande." %>
<% @atelier2_path = image_path ENV['ATELIER2'], class: "img-city", alt: "Philippe Nerriere réalise toutes les pièces en morta dans son atelier à Guérande." %>

<% if @admin %>
  <% if @admin.atelier1photo.present? %>
      <% @atelier1 = cl_image_tag @admin.atelier1photo.path, class: "img-avatar", alt: "Philippe Nerriere réalise toutes les pièces en morta dans son atelier à Guérande."%>
      <% @atelier1_path = cl_image_path @admin.atelier1photo.path, class: "img-avatar", alt: "Philippe Nerriere réalise toutes les pièces en morta dans son atelier à Guérande."%>
  <% end %>
  <% if  @admin.atelier2photo.present? %>
    <% @atelier2 = cl_image_tag @admin.atelier2photo.path, class: "img-city", alt: "Philippe Nerriere réalise toutes les pièces en morta dans son atelier à Guérande." %>
    <% @atelier2_path = cl_image_path @admin.atelier2photo.path, class: "img-city", alt: "Philippe Nerriere réalise toutes les pièces en morta dans son atelier à Guérande." %>
  <% end %>
<% end %>

app/views/shared/_darktheme_home_pics.html.erb
<% @darktheme1photopath = image_path ENV['DARKTHEMEPHOTO'] %>
<% @darktheme2photopath = image_path ENV['DARKTHEMEPHOTO'] %>
<% @darktheme3photopath = image_path ENV['DARKTHEMEPHOTO'] %>
<% @darktheme4photopath = image_path ENV['DARKTHEMEPHOTO'] %>
<% if @admin %>
  <% if  @admin.darktheme1photo.present? %>
    <% @darktheme1photopath = cl_image_path @admin.darktheme1photo.path %>
  <% end %>
  <% if  @admin.darktheme2photo.present? %>
    <% @darktheme2photopath = cl_image_path @admin.darktheme2photo.path %>
  <% end %>
  <% if  @admin.darktheme3photo.present? %>
    <% @darktheme3photopath = cl_image_path @admin.darktheme3photo.path %>
  <% end %>
  <% if  @admin.darktheme4photo.present? %>
    <% @darktheme4photopath = cl_image_path @admin.darktheme4photo.path %>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-default" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-default" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-error alert-dismissible alert-default" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_flashes_darktheme.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-darktheme" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-darktheme" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-error alert-dismissible alert-darktheme" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_footer_darktheme.html.erb
<div id="footer">
  <div class="contact-default">
    <a href="https://www.google.fr/maps/place/<%=ENV['ADDRESS']%>" target="blank">
      <div class="icone-bloc">
        <i class="fa fa-map"></i>
        <h6 class="info-text hidden-xs"><%=ENV['ADDRESS'].gsub('+',' ')%></h6>
      </div>
    </a>
    <div class="icone-bloc">
      <i class="fa fa-envelope"></i>
      <h6 class="info-text middle-text info-text-1"> <%= link_to "#{ENV['EMAIL']}",  "mailto:#{ENV['EMAIL']}"%></h6>
    </div>
    <div class="icone-bloc">
      <i class="fa fa-phone"></i>
      <h6 class="info-text info-text-2"><%= link_to "#{ENV['TELEPHONE']}", "tel:#{ENV['TELEPHONE']}" %></h6>
    </div>
    <% if user_signed_in? %>
      <div class="icone-bloc">
        <i class="fa fa-sign-out-alt"></i>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <h6 class="info-text info-text-3"><%=t(:unconnect)%></h6>
        <% end %>
      </div>
    <% else %>
      <div class="icone-bloc">
        <i class="fa fa-sign-in-alt"></i>
        <%= link_to new_user_session_path, class: "navbar-item navbar-link" do %>
          <h6 class="info-text info-text-3"><%=t(:connect)%></h6>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="footer-center-infos">
    <div class="center-bloc">
      <%= link_to t(:cgv_short), cgv_path , class: "first-a" %>
      <%= link_to t(:data), legal_path %>
    </div>
  </div>
  <div class="mylink">
    <%= link_to @dev_redirection || session[:dev_redirection_default], title: "Créez votre boutique en ligne avec l'agence de Guillaume Crouillere" do %>
      <%= image_tag  'lego.svg', alt: "Guillaume Crouillere - Developpeur WEB indépendant"%>
  <% end %>
  </div>
</div>

app/views/shared/_index_strip.html.erb
<%= render  'shared/images_box_inclined',
    image_1: cl_image_path(@top_category.photo_1.path),
    image_2: cl_image_path(@top_category.photo_2.path),
    mobile: false,
    image1_left: "0px",
    title: "<h1>Les créations uniques en Morta</h1>" %>

app/views/shared/_lighttheme_filter.html.erb
<div id="ceramique-filters-content-lighttheme">
  <%= render 'shared/ceramiques_filter', device: "mobile", show_cross: true, theme: "white" %>
</div>

app/views/shared/_logo_pic.html.erb
<% @logositepictag = image_tag ENV['LOGOSITE'] , alt: "Accueil de la boutique en ligne" %>
<% if @admin %>
  <% if  @admin.logophoto.present? %>
    <% @logositepictag = cl_image_tag @admin.logophoto.path, alt: "Accueil de la boutique en ligne" %>
  <% end %>
<% end %>

app/views/shared/_product_image_overlay.html.erb
<% if session[:zoom_message] < 1 %>
  <style>
  .ceramique-images .img-front {
       filter:brightness(55%);
  }
  </style>
  <div class="imageoverlay">
    <div class="overlay-text">
      <p><%=t(:zoom)%></p>
      <%=image_tag "mousewheel.svg", class: "mousewheel"%>
      <%=image_tag "fingerzoom.svg", class: "mousewheel"%>
      <h5 class="overlay-ok">OK</h5>
    </div>
  </div>
<% end %>

app/views/shared/_shipping_cost_bloc.html.erb
<div class="shipping-cost">
  <h5 class="port"><%=t(:total_port)%></h5>
  <%= simple_form_for (@order.user || User.new) do |f| %>
    <% if @order.user %>
      <%= f.input :country, label: false, selected: @order.user.country %>
    <% else %>
      <%= f.input :country, label: false, selected: "FR" %>
    <% end %>
  <% end %>
  <h5 class="port port-cost"> : <%= humanized_money(@port) %> <%= currency_symbol %></h5>
</div>

app/views/shared/_shipping_cost_bloc_mobile.html.erb
<div class="shipping-cost">
  <h5 class="port"><%=t(:total_port)%></h5>
  <%= simple_form_for (@order.user || User.new) do |f| %>
    <% if @order.user %>
      <%= f.input :country, label: false, selected: @order.user.country, :input_html => { :id => "user_country_mobile" } %>
    <% else %>
      <%= f.input :country, label: false, selected: "FR", :input_html => { :id => "user_country_mobile" } %>
    <% end %>
  <% end %>
  <h5 class="port port-cost"> : <%= humanized_money(@port) %> <%= currency_symbol %></h5>
</div>

app/views/shared/_socialbuttons.html.erb
<div class="social-buttons">
    <a class="twitter-share-button" href="https://twitter.com/intent/tweet?<%=@twitter_url%>">
      <i class="fab fa-twitter-square"></i>
    </a>
    <a href="https://www.pinterest.com/pin/create/button/" data-pin-do="buttonPin" data-pin-custom="true">
      <i class="fab fa-pinterest-square"></i>
    </a>
    <a id=<%=@facebookid%> href="#">
      <i class="fab fa-facebook-square"></i>
    </a>
  </div>

app/views/shared/_subscribe_default.html.erb
<% unless session[:email]%>
  <div class="subscribe-text">
    <h2><%=t(:contact)%></h2>
  </div>
  <form action="/user-subscribe" method="post" authenticity_token="true" class="subscribe-form">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="text" name="user[email]" id="email" placeholder="<%=t(:email_adress)%>" class="subscribe-input">
    <input type="text" name="user[first_name]" id="first_name" placeholder="<%=t(:first_last_name)%>" class="subscribe-input">
    <textarea name="user[tracking]" id="tracking" placeholder="<%=t(:send_your_message)%>" class="subscribe-input textarea"></textarea>
    <input type="submit" class="btn btn-primary" value="<%=t(:send)%>">
  </form>
<% end %>