config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "app_specific_registration/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  mount Attachinary::Engine => "/attachinary"

  get '/payments/create_stripe_payment', to: 'payments#create_stripe_payment'

  scope do
    resources :ceramiques, path: ENV['MODEL'], only: [:create, :index, :destroy, :show, :update]
  end

  resources :orders, only: [:show, :create, :destroy] do
    resources :payments, only: [:new, :create]
  end

  resources :lessons, only: [:new, :create, :destroy, :show]

  resources :users, only: [:update, :create]

  resources :articles, only: [:new, :index, :show, :update, :create, :destroy, :edit]

  #Stages
  get '/stage_confirmation', to: 'lessons#stage_confirmation'
  get '/stage_payment_confirmation', to: 'lessons#stage_payment_confirmation'

  #Pages
  get '/confirmation', to: 'pages#confirmation'
  get '/agenda', to: 'pages#agenda'
  get '/professionnels', to: 'pages#professionnels'
  get '/presse', to: 'pages#presse'
  get '/sites_partenaires', to: 'pages#sites_partenaires'
  get '/cgv', to: 'pages#cgv'
  get '/atelier', to: 'pages#atelier'
  get '/morta', to: 'pages#morta'
  get '/la_briere', to: 'pages#la_briere'
  get '/temoignages', to: 'pages#temoignages'
  get '/sur_mesure', to: 'pages#sur_mesure'
  get '/contact', to: 'pages#contact'
  get '/cgv', to: 'pages#cgv'
  get '/legal', to: 'pages#legal'
  get '/google906057532e2dbb7e', to: 'pages#google906057532e2dbb7e'
  get '/robots.txt', to: 'pages#robots', :defaults => { :format => 'txt' }

  #Sitemap
  get 'sitemap.xml', :to => 'sitemap#sitemap', :defaults => { :format => 'xml' }

  #Subscribe
  post '/user-subscribe', to: "users#subscribe"

  #Root
  root to: 'pages#home'

  #Errors
  get "/404", to: "errors#error_404"

  #API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :shipping_categories, only: [:show]
      resources :promos, only: [:show]
    end
  end

  #Position management through JS
  get '/ceramiques/update_positions_after_swap_in_admin', to: "ceramiques#update_positions_after_swap_in_admin"

end

app/models/ceramique.rb
class Ceramique < ApplicationRecord
  include AlgoliaSearch
  after_initialize :default_values
  # extend FriendlyId

  extend Mobility
  translates :name, type: :string, fallbacks: { fr: :en, en: :fr }, locale_accessors: [:en, :fr]
  translates :description, type: :text, fallbacks: { fr: :en, en: :fr }, locale_accessors: [:en, :fr]

  algoliasearch do
    add_attribute :translated_name_fr
    add_attribute :translated_name_en
    add_attribute :translated_description_fr
    add_attribute :translated_description_en
    add_attribute :translated_category_en
    add_attribute :translated_category_fr
    attribute :category
  end

  belongs_to :category
  has_one :top_category, through: :category
  belongs_to :offer, required: false
  has_attachments :photos, maximum: 4, dependent: :destroy
  has_many :basketlines

  monetize :price_cents
  monetize :support_price_cents

  validates :photos, presence: true
  validates :category, presence: true
  validates :name, presence: true
  validates :description, presence: true

  validates :weight, presence: true, numericality: { greater_than: 0, less_than: 30001 , only_integer: true, message: 'Le poids doit être compris entre 1 et 30 000 grammes. Pas d\'expédition Colissimo possible en dehors de cette plage.' }
  validates :stock, presence: true, numericality: { only_integer: true , message: 'Doit être un entier'}
  validates :price_cents, presence: true, numericality: { greater_than: 0 , message: 'Doit être un entier supérieur à 0' }

  def to_param
    name_param = self.send(I18n.locale == :fr ?
      (name_fr.present? ? "name_fr" : (name_en.present? ? "name_en" : "name")) :
      (name_en.present? ? "name_en" : "name")) || ""
    category_param = category.send(I18n.locale == :fr ?
      (category.name_fr.present? ? "name_fr" : (category.name_en.present? ? "name_en" : "name")) :
      (category.name_en.present? ? "name_en" : "name")) || ""
    [id, name_param.parameterize, category_param.parameterize].join("-")
  end

  def translated_name_fr
    self.name_fr
  end

  def translated_name_en
    self.name_en
  end

  def translated_description_fr
    self.description_fr
  end

  def translated_description_en
    self.description_en
  end

  def translated_category_fr
    self.category.name_fr
  end

  def translated_category_en
    self.category.name_en
  end

  private
    def default_values
      self.support_price_cents ||= 0
    end
end

app/controllers/ceramiques_controller.rb
class CeramiquesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @dev_redirection = "https://www.creermonecommerce.fr/product_claim_details"
    @ceramiques = Ceramique.all
    Offer.where(showcased: true).first ? (Offer.where(showcased: true).first.ceramiques.present? ? @front_offer = Offer.all.where(showcased: true).includes(:ceramiques).first : nil) : nil
    @front_offer ? @ceramiques_to_display_in_offer = Ceramique.all.where(offer: @front_offer) : nil
    clean_orders
    if params[:all].present?
      @ceramiques
    else
      filter_by_category if ( params[:categories].present? || params[:top_category].present? )
      filter_by_offer if params[:offer].present?
      filter_globally if params[:search].present?
      filter_by_price if params[:prix_max].present?
    end
    @ceramiques = Ceramique.where(id: @ceramiques.map(&:id)).order(position: :asc).order(updated_at: :desc).includes(:photo_files).includes(:offer)
    index_strip_photos(params[:univers])
    @twitter_url = request.original_url.to_query('url')
    @facebookid = ""
    render "index_#{@active_theme.name}"
  end

  def show
    session[:zoom_message] ? session[:zoom_message] += 1 : session[:zoom_message] = 0
    @dev_redirection = "https://www.creermonecommerce.fr/produits"
    clean_orders
    @ceramique = Ceramique.find(params[:id])
    @same_category_products = @ceramique.category.ceramiques - [@ceramique]
    @twitter_url = request.original_url.to_query('url')
    render "show_#{@active_theme.name}"
  end

  def update
    @ceramique = Ceramique.find(params[:id])
    @fieldvalue =  @ceramique.send(get_editing_field)
    if @ceramique.update(ceramique_params)
      render json: @ceramique
    else
      render json: {id: @ceramique.id, fieldvalue: @fieldvalue, errors: @ceramique.errors}, status: :unprocessable_entity
    end
  end

  def update_positions_after_swap_in_admin
    params[:finalPositions].gsub("]","").gsub("[", "").split(",").map(&:to_i).each_with_index do |position, index|
      Ceramique.find(position).update(position: index + params[:startingPosition].to_i)
    end
    @ceramiques = Ceramique.all.order(position: :asc).order(updated_at: :desc)
    render json: @ceramiques
  end

  private

  def clean_orders
    Order.all.each do |order|
      if ((Time.now - order.created_at)/60/60 > ENV['BASKETDURATION'].to_f && order.state == "pending" && order.lesson.blank?) || ((Time.now - order.created_at)/60/60 > 24 && order.state == "payment page" && order.lesson.blank?)
        order.basketlines.each do |basketline|
          ceramique = basketline.ceramique
          ceramique.update(stock: ceramique.stock + basketline.quantity)
        end
        if session[:order]
          wip_local_order = Order.find(session[:order])
          session[:order] = nil if order == wip_local_order
        end
        order.update(state: "lost")
      end
    end
  end

  def filter_by_category
    if params[:top_category]
      query = params[:top_category]
      @ceramiques = @ceramiques.joins(:top_category).merge(TopCategory.i18n { name.matches(query) })
    else
      categories = params[:categories].map {|category| "%#{category}%" }
      @ceramiques = @ceramiques.joins(:category).merge(Category.i18n { name.matches_any(categories) })
    end
  end

  def filter_by_price
    @ceramiques = @ceramiques.joins(:offer).where("price_cents * (1 - discount) <= ? AND price_cents * (1 - discount) >= ? ", params[:prix_max].to_i * 100, params[:prix_min].to_i * 100) +
                  @ceramiques.where('offer_id IS NULL').where("price_cents <= ? AND price_cents >= ?", params[:prix_max].to_i * 100, params[:prix_min].to_i * 100)
  end

  def filter_by_offer
    @ceramiques = @ceramiques.where(offer: @front_offer)
  end

  def filter_globally
    raw_json = Ceramique.raw_search(params[:search])
    ceramiques_ids = raw_json["hits"].map {|hit| hit["objectID"].to_i}
    @ceramiques = @ceramiques.where(id: ceramiques_ids)
  end

  def index_strip_photos(params_univers)
    if params_univers
      @photo1 = params_univers + "1.jpg"
      @photo2 = params_univers + "2.jpg"
    end
  end

  def ceramique_params
    if params[:ceramique][:category].present?
      params.require(:ceramique).permit(:name, :stock, :weight, :price_cents, :description).merge(category_id: Category.i18n.where(name: params[:ceramique][:category]).first.id)
    else
      params.require(:ceramique).permit(:name, :stock, :weight, :price_cents, :description)
    end
  end

  def get_editing_field
    params.require(:ceramique).permit(:name, :stock, :weight, :price_cents, :description, :category).to_h.map {|k, v| k }.join
  end
end

app/views/ceramiques/index_darktheme.html.erb
<% content_for(:title_tag) do %>
  <%= t(:index_title)%>
<% end %>
<% if @front_offer %>
  <% content_for(:meta_image) do %>
    <%= cl_image_path @front_offer.ceramiques.first.photos[0].path %>
  <% end %>
  <% content_for(:description) do %>
    <% @front_offer.discount > 0 ? discount = t(:discount_percentage, amount: "#{(@front_offer.discount * 100).to_i}") : discount = "" %>
    <%= "#{@front_offer.title} - #{discount} - #{@front_offer.description}".squish %>
  <% end %>
<% else %>
  <% content_for(:description) do %>
    <%= t(:index_description)%>
  <% end %>
<% end %>


<div class="container">
  <div class="row">
<!-- INDEX H1 :  EITHER A DISCOUNT OFFER DIV, OR A SIMPLE H1 -->
  <% if @front_offer && params[:offer] == nil %>

    <div class="hidden-xs hidden-sm col-md-12 info-top-darktheme">
      <%= render 'shared/general_info_bubble_darktheme' %>
    </div>
    <div class="h1-index mobile hidden-md hidden-lg">
      <h1><%=t(:main_index_h1)%></h1>
      <hr>
    </div>
  <% elsif params[:offer].present? %>
    <div class="h1-index hidden-xs hidden-sm">
      <h1> <%= @front_offer.title %> <%=t(:offer_products)%></h1>
      <hr>
    </div>
  <% else %>
    <div class="h1-index hidden-xs hidden-sm">
      <h1><%=t(:main_index_h1)%></h1>
      <hr>
    </div>
    <div class="h1-index mobile hidden-md hidden-lg">
      <h1> <%= t(:unique_creation)%></h1>
      <hr>
    </div>
  <% end %>

<!-- LAPTOP -->
    <div class="hidden-xs hidden-sm hidden-md col-lg-3">
      <div id="ceramique-filters-content-darktheme">
        <%= render 'shared/ceramiques_filter', device: "", show_cross: false, theme: "dark" %>
      </div>
    </div>

    <% if  @ceramiques.present? %>
      <div class="col-xs-12 col-lg-9 ceramique-list">
        <% @ceramiques.each_with_index do |ceramique, index| %>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <%= link_to ceramique_path(ceramique), title: "#{ceramique.name}", class: "cardlink" do %>
              <% ceramique == @ceramiques.last ? additionnal_class = "last-ceramique" : additionnal_class = "" %>
              <div class="ceramiquecard-darktheme <%=additionnal_class%>">
                <div class="ceramiquecardimage ceramiquecardimage-<%=index%>">
                    <style>
                    .ceramiquecardimage-<%=index%> {
                      background-image: url(<%= cl_image_path ceramique.photos[0].path, quality: "auto" %>);
                      background-size: cover;
                      background-position-y: center;
                      background-position-x: center;
                    }
                  </style>
                </div>
                <% if ceramique.offer%>
                  <% if ceramique.offer.discount > 0 %>
                    <p class="discount-offer">-<%= (ceramique.offer.discount * 100).to_i %>%</p>
                    <div class="ribbon"></div>
                  <% end %>
                <% end %>
                <% if  ceramique.stock == 0 %>
                  <div class="ceramiques-card-circle soldout darktheme-circle"><p>Epuisé</p></div>
                <% end %>
                <div class="transparent-div"></div>
                <div class="ceramique-card-text">
                  <h2 class="card-mobile-h2 hidden-md hidden-lg"> <%= ceramique.name.capitalize%> </h2>
                  <h2 class="card-h2 hidden-xs hidden-sm"> <%= ceramique.name.capitalize%> </h2>
                  <div class="prices-box">
                    <% ceramique.offer ? discount =  ceramique.offer.discount : discount = 0 %>
                      <h2 class="prix-index hidden-xs hidden-sm"><%= humanized_money(ceramique.price * (1 - discount))%> <%= currency_symbol %></h2>
                      <% if ceramique.offer %>
                        <% if ceramique.offer.discount > 0 %>
                          <h3 class="previous-price hidden-xs hidden-sm"><%= humanized_money(ceramique.price)%> <%= currency_symbol %></h3>
                        <% end %>
                      <% end %>
                    <% if ceramique.offer %>
                      <% if ceramique.offer.discount > 0 %>
                        <div class="allpricesmobile-w hidden-md hidden-lg">
                          <h2 class="prix-index-mobile"><%= humanized_money(ceramique.price * (1 - discount))%> <%= currency_symbol %></h2>
                          <h3 class="previous-price-mobile"><%= humanized_money(ceramique.price)%> <%= currency_symbol %></h3>
                        </div>
                      <% else %>
                        <div class="allpricesmobile-w-zero hidden-md hidden-lg">
                          <h2 class="prix-index-mobile"><%= humanized_money(ceramique.price * (1 - discount))%> <%= currency_symbol %></h2>
                        </div>
                      <% end %>
                    <% else %>
                      <div class="allpricesmobile-wo hidden-md hidden-lg">
                        <h2 class="prix-index-mobile"><%= humanized_money(ceramique.price * (1 - discount))%> <%= currency_symbol %></h2>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="ol-xs-12 col-lg-9 no-ceramique-list">
        <div class="no-ceramique">
          <p><%=t(:no_product)%></p>
          <%= link_to t(:all_products), ceramiques_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>

<!-- MOBILE -->

<div class="hidden-lg">
  <div id="ceramique-filters-content-mobile-darktheme">
      <%= render 'shared/ceramiques_filter', { device: "mobile", show_cross: true, theme: "dark" } %>
  </div>
</div>

<div id="mobile-filter-search-darktheme" class="hidden-lg">
  <i class="fa fa-search" aria-hidden="true"></i>
</div>

  </div>
</div>

<%= render 'shared/schema_org_jsons/ceramiques_index_json' %>
<% content_for(:after_js) do %>
  <script
  type="text/javascript"
  async defer
  src="//assets.pinterest.com/js/pinit.js"
  data-pin-round="true"
  data-pin-tall="15px"
></script>
<%= render 'shared/facebookshare' %>
<%= render 'shared/algolia_search' %>
<% end %>

app/views/ceramiques/index_lighttheme.html.erb
<% content_for(:title_tag) do %>
  <%= t(:index_title)%>
<% end %>
<% if @front_offer %>
  <% content_for(:meta_image) do %>
    <%= cl_image_path @front_offer.ceramiques.first.photos[0].path %>
  <% end %>
  <% content_for(:description) do %>
    <% @front_offer.discount > 0 ? discount = t(:discount_percentage, amount: "#{(@front_offer.discount * 100).to_i}") : discount = "" %>
    <%= "#{@front_offer.title} - #{discount} - #{@front_offer.description}".squish %>
  <% end %>
<% else %>
  <% content_for(:description) do %>
    <%= t(:index_description)%>
  <% end %>
<% end %>

<%= render 'shared/lighttheme_photo_loading'%>

<div class="container-lighttheme">
  <div class="row">
    <% if  @ceramiques.present? %>
       <% @ceramiques.each_with_index do |ceramique, index| %>
          <div class="col-xs-6 col-sm-4 col-md-3 lighttheme-ceramiquecard-col">
            <%= link_to ceramique_path(ceramique), title: "#{ceramique.name}", class: "cardlink-lighttheme" do %>
              <div class="ceramiquecard-lighttheme">
                <div class="img-container ceramique-front-image-<%=index%>">
                  <style>
                    .ceramique-front-image-<%=index%> {
                      background-image: url(<%= cl_image_path ceramique.photos[0].path, quality: "auto" %>);
                    }
                    <% if ceramique.photos[1]%>
                    .ceramique-front-image-<%=index%>:hover {
                      <% if  cl_image_path ceramique.photos[1]%>
                        background-image: url(<%= cl_image_path ceramique.photos[1].path, quality: "60" %>);
                      <% end %>
                    }
                    <% end %>
                  </style>
                  <% if  ceramique.stock == 0%>
                    <div class="ceramiques-card-circle soldout lighttheme-circle"><p>Epuisé</p></div>
                  <% elsif ceramique.offer%>
                    <% if ceramique.offer.discount > 0 %>
                      <div class="ceramiques-card-circle discount-circle lighttheme-circle"><p>-<%= (ceramique.offer.discount * 100).to_i %>%</p></div>
                    <% end %>
                  <% end %>
                </div>
                <h2><%= ceramique.name.capitalize%></h2>
                <% ceramique.offer ? discount =  ceramique.offer.discount : discount = 0 %>
                <% ceramique.offer ? ondiscount =  "ondiscount" : ondiscount =  "" %>
                <div class="prices-ceramiq-card-lighttheme">
                  <h3 class="prix-index <%=ondiscount%>"><%= humanized_money(ceramique.price * (1 - discount))%> <%= currency_symbol %></h2>
                  <% if ceramique.offer %>
                    <% if ceramique.offer.discount > 0 %>
                      <h3 class="previous-price"><%= humanized_money(ceramique.price)%> <%= currency_symbol %></h3>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
      <% end %>
      <% else %>
        <div class="col-xs-12 no-ceramique-list">
          <div class="no-ceramique">
            <p><%=t(:no_product)%></p>
            <%= link_to t(:all_products), ceramiques_path, class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

<%= render 'shared/subscribe' %>

<%= render 'shared/schema_org_jsons/ceramiques_index_json' %>

app/views/ceramiques/show.html.erb
<% content_for(:description) do %>
<%= @ceramique.name.capitalize %>. Prix : <%= humanized_money(@ceramique.price)%> €. Livraison sous 3 semaines.
<% end %>
<% content_for(:title_tag) do %>
Les <%="#{ENV['MODEL']} de #{ENV['FIRSTNAME'].capitalize} #{ENV['LASTNAME'].capitalize}"%> - <%= @ceramique.name.capitalize %>
<% end %>
<% content_for(:meta_image) do %>
  <%= cl_image_path @ceramique.photos[0].path %>
<% end %>
<% content_for(:meta_description) do %>
  <%= ("#{@ceramique.name} : #{@ceramique.description}. Prix: #{humanized_money(@ceramique.price)} €").squish %>
<% end %>


<div class="container">

<!-- LAPTOP -->
  <div class="hidden-xs hidden-sm">

    <div class="row">
      <div class="col-md-12">
        <div class="product-show text center">

          <div class="col-md-6 product-show-half-top-wrapper">
          <div class="ceramique-images">
            <img class="img-front" id="zoom01" src="<%= cl_image_path @ceramique.photos[0].path %>" data-zoom-image="<%= cl_image_path @ceramique.photos[0].path %>" alt="<%=@ceramique.name%>">
            <div class="images">
              <% @ceramique.photos.each_with_index do |photo, index| %>
                <% if index < 4 %>
                  <img class="thumbnail" src="<%= cl_image_path @ceramique.photos[index].path %>" alt="<%=@ceramique.name%>">
                <% end %>
              <% end %>
            </div>
          </div>
          </div>

          <div class="col-md-6 product-show-half-top-wrapper">
          <div class="info-add-basket">
            <div class="description">
              <h1> <%= @ceramique.name.capitalize%> </h1>
              <%= facebook_share_id("facebookshare") %>
              <p class="description"> <%= @ceramique.description.gsub(/\n/, '<br>').html_safe%> </p>
              <hr>
            </div>
            <div class="prix-form">
              <% @ceramique.offer ? discount =  @ceramique.offer.discount : discount = 0 %>
              <h2> <%= humanized_money(@ceramique.price * (1 - discount))%> <%= currency_symbol %> </h2>
              <% if @ceramique.offer %>
                <% if @ceramique.offer.discount > 0 %>
                  <h3 class="previous-price"><%= humanized_money(@ceramique.price)%> <%= currency_symbol %></h3>
                <% end %>
              <% end %>
              <% if  @ceramique.stock > 0 %>
                <form action="/orders" method="post" authenticity_token="true" class="form">
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                  <div class="qte">
                    <label for="quantity">Quantité </label>
                    <select name="quantity">
                      <% for i in 1..@ceramique.stock %>
                        <option value="<%= i %>"><%= i %></option>
                      <% end %>
                    </select>
                  </div>
                  <input type="hidden" name="ceramique" value="<%= @ceramique.id%>">
                  <button type="submit" class="pull-right btn btn-primary order">
                    <i class="fa fa-plus""></i> Ajouter au panier
                  </button>
                </form>
              <% else %>
                  <h2 class="stock0">Stock épuisé</h2>
              <% end %>
            </div>
          </div>
          </div>

        </div>
      </div>
    </div>

    <div class="link_to_list_div">
      <%= link_to ceramiques_path, class: "link_to_list" do %>
        <span><i class="fa fa-arrow-right"></i> Liste des <%= ENV['MODEL'].capitalize%></span>
      <% end %>
    </div>

    <% if @same_category_products != [] %>

    <hr class="product-show-separator">

    <div class="row">
      <div class="col-sm-12 same-category-products">
          <h2>Retrouvez d'autres produits dans la même catégorie: </h2>
          <div class="same-category-products-cards">
            <% @same_category_products.each_with_index do |ceramique, index|%>
              <% if index == 0 || (index)%3 == 0 %>
                <div class="card-separator">
              <% end %>
                <div class="col-sm-4 same-category-product-card">
                  <%= link_to ceramique_path(ceramique) , title: "#{ceramique.name}", class: "same-category-product-card-link"  do %>
                  <img class="same-product-photo" src="<%= cl_image_path ceramique.photos[0].path %>" alt="<%=ceramique.name%>">
                  <div class="same-category-product-card-text">
                    <p class="ceramique-name"><%= ceramique.name.capitalize%></p>
                    <% ceramique.offer ? discount =  ceramique.offer.discount : discount = 0 %>
                    <% if discount > 0 %>
                      <p class="prix-index"><%= humanized_money(ceramique.price * (1 - discount))%> <%= currency_symbol %></h2>
                      <p class="previous-price"><%= humanized_money(ceramique.price)%> <%= currency_symbol %></h3>
                    <% else %>
                      <p class="prix-index-wo-discount"><%= humanized_money(ceramique.price)%> <%= currency_symbol %></h2>
                    <% end %>
                  </div>
                  <% end %>
                </div>
              <% if ceramique == @same_category_products.last || index == 2 || (index + 1)%3 == 0 %>
                </div>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>

    <% end %>

  </div>

<!-- MOBILE -->
  <!-- <div class="hidden-md hidden-lg"> -->
    <div class="row">
      <div class="col-xs-12 hidden-md hidden-lg">

        <div class="head">
          <%= facebook_share_id("facebooksharemobile") %>
          <h1> <%= @ceramique.name.capitalize%> </h1>
          <div class="image-xs-sm">
            <img class="img-front" src="<%= cl_image_path @ceramique.photos[0].path %>" alt="<%=@ceramique.name%>">
          </div>
        </div>
        <div class="other-imgs other-mobile">
          <div class="images-mobile">
            <% @ceramique.photos.each_with_index do |photo, index| %>
              <% if index < 4 %>
                <img class="thumbnail" src="<%= cl_image_path @ceramique.photos[index].path %>" alt="<%=@ceramique.name%>">
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="product-show-mobile text center">
          <div class="info-add-basket">
            <div class="description">
              <p class="description"> <%= @ceramique.description.gsub(/\n/, '<br>').html_safe %> </p>
              <hr>
            </div>
            <div class="prix-form">
              <% @ceramique.offer ? discount =  @ceramique.offer.discount : discount = 0 %>
              <h2> <%= humanized_money(@ceramique.price * (1 - discount))%> <%= currency_symbol %> </h2>
              <% if @ceramique.offer %>
                    <% if @ceramique.offer.discount > 0 %>
                      <h3 class="previous-price"><%= humanized_money(@ceramique.price)%> <%= currency_symbol %></h3>
                    <% end %>
                  <% end %>
              <% if  @ceramique.stock > 0 %>
                <form action="/orders" method="post" authenticity_token="true" class="form">
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                  <div class="qte">
                    <label for="quantity">Qté </label>
                    <select name="quantity">
                      <% for i in 1..@ceramique.stock %>
                        <option value="<%= i %>"><%= i %></option>
                      <% end %>
                    </select>
                  </div>
                  <input type="hidden" name="ceramique" value="<%= @ceramique.id%>">
                  <button type="submit" class="pull-right btn btn-primary order">
                    <i class="fa fa-plus""></i> <i class="fa fa-shopping-cart"></i>
                  </button>
                </form>
              <% else %>
                  <h2 class="stock0">Stock épuisé</h2>
              <% end %>
            </div>
          </div>
        </div>

        <div class="mobile-link">
          <%= link_to ceramiques_path do %>
            <span><i class="fa fa-arrow-right"></i> Liste des <%= ENV['MODEL'].capitalize%></span>
          <% end %>
        </div>

      </div>
    </div>
  <!-- </div> -->

</div>

<% content_for(:after_js) do %>
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "<%=@ceramique.name.capitalize%>",
    "description": "<%=@ceramique.description%>",
    "offers": {
      "@type": "Offer",
      "price": "<%= humanized_money(@ceramique.price)%>",
      "priceCurrency": "€"
    },
    "url": "<%=request.original_url%>",
    "image": "<%=cl_image_path @ceramique.photos[0].path%>"
  }
  </script>
  <script
    type="text/javascript"
    async defer
    src="//assets.pinterest.com/js/pinit.js"
    data-pin-round="true"
    data-pin-tall="15px"
></script>
<%= render 'shared/facebookshare' %>
<% end %>