config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "app_specific_registration/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  mount Attachinary::Engine => "/attachinary"

  get '/payments/create_stripe_payment', to: 'payments#create_stripe_payment'

  scope do
    resources :ceramiques, path: ENV['MODEL'], only: [:create, :index, :destroy, :show, :update]
  end

  resources :orders, only: [:show, :create, :destroy] do
    resources :payments, only: [:new, :create]
  end

  resources :lessons, only: [:new, :create, :destroy, :show]

  resources :users, only: [:update, :create]

  resources :articles, only: [:new, :index, :show, :update, :create, :destroy, :edit]

  #Stages
  get '/stage_confirmation', to: 'lessons#stage_confirmation'
  get '/stage_payment_confirmation', to: 'lessons#stage_payment_confirmation'

  #Pages
  get '/confirmation', to: 'pages#confirmation'
  get '/agenda', to: 'pages#agenda'
  get '/professionnels', to: 'pages#professionnels'
  get '/presse', to: 'pages#presse'
  get '/sites_partenaires', to: 'pages#sites_partenaires'
  get '/cgv', to: 'pages#cgv'
  get '/atelier', to: 'pages#atelier'
  get '/morta', to: 'pages#morta'
  get '/la_briere', to: 'pages#la_briere'
  get '/temoignages', to: 'pages#temoignages'
  get '/sur_mesure', to: 'pages#sur_mesure'
  get '/contact', to: 'pages#contact'
  get '/cgv', to: 'pages#cgv'
  get '/legal', to: 'pages#legal'
  get '/google906057532e2dbb7e', to: 'pages#google906057532e2dbb7e'
  get '/robots.txt', to: 'pages#robots', :defaults => { :format => 'txt' }

  #Sitemap
  get 'sitemap.xml', :to => 'sitemap#sitemap', :defaults => { :format => 'xml' }

  #Subscribe
  post '/user-subscribe', to: "users#subscribe"

  #Root
  root to: 'pages#home'

  #Errors
  get "/404", to: "errors#error_404"

  #API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :shipping_categories, only: [:show]
      resources :promos, only: [:show]
    end
  end

  #Position management through JS
  get '/ceramiques/update_positions_after_swap_in_admin', to: "ceramiques#update_positions_after_swap_in_admin"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order, only: [:create, :new, :create_stripe_payment]
  before_action :logistic_check, only: [:new]

  def new
    if @order.state == "lost"
      flash[:notice] = t(:expired_basket)
      redirect_to ceramiques_path and return
    end

    @payment_theme = @active_theme.name
    final_order_amount
    @order.take_away ? @final_amount = @order.amount_cents : @final_amount = @order.amount_cents + @order.port_cents

    session = Stripe::Checkout::Session.create(
      customer_email: @order.user ? @order.user.email : "",
      payment_method_types: ['card'],
      line_items: [{
        name: 'EDEN BLACK',
        description: "Paiement pour #{@order.ceramique || "lesson"}",
        amount: @final_amount,
        currency: 'eur',
        quantity: 1,
      }],
      success_url: payments_create_stripe_payment_url(order_id: @order.id),
      cancel_url: new_order_payment_url(@order),
    )

    @stripe_session = session["id"]
    @order.update(stripe_session: session["id"])
    @order.take_away ? @order_in_js = @order.amount_cents : @order_in_js = @order.amount_cents + @order.port_cents
    gon.order_in_js = @order_in_js.to_f / 100
  end

  def create_stripe_payment
    session = Stripe::Checkout::Session.retrieve(@order.stripe_session)
    payment_intent = Stripe::PaymentIntent.retrieve(session["payment_intent"])
    status = payment_intent["status"]

    if status == "succeeded"
      document_order_basketlines
      @order.update(stripe_payment_intent: payment_intent, state: 'paid', method: 'stripe')
      sends_mails_after_order
    else
      flash[:notice] = t(:payment_failure)
      redirect_to new_order_payment_url(@order)
    end
  end

  def create
    # STRIPE
    if @order.state == "lost"
      flash[:error] = t(:expired_no_payment)
      redirect_to ceramiques_path and return
    end

    if params[:method] == "paypal"
      if params[:status] == "success"
        @order.update(state: 'paid', method: "paypal")
        document_order_basketlines
        sends_mails_after_order
      end
    end
  end

  private

  def sends_mails_after_order
    @lesson =  @order.lesson
    unless @lesson.present?
      # SEND EMAILS
      @user = current_user
      @amount = @order.amount
      OrderMailer.confirmation_mail_after_order(@user, @order).deliver_now
      OrderMailer.mail_francoise_after_order(@user, @order).deliver_now
      # CLEAR SESSION AND REDIRECT TO CONFIRMATION
      session[:order] = nil
      redirect_to confirmation_path and return
    else
      # SEND EMAILS
      LessonMailer.mail_user_after_lesson_payment(@lesson, @user).deliver_now
      LessonMailer.mail_francoise_after_lesson_payment(@lesson, @user).deliver_now
      redirect_to stage_payment_confirmation_path and return
    end
  end

  def set_order
    @order = Order.find(params[:order_id])
    @order.update(state: "payment page") unless @order.state == "lost"
    @order.update(user: current_user) unless @order.user
  end

  def logistic_check
    params[:take_away] == "on" ? @order.update(take_away: true) : @order.update(take_away: false)
  end

  def final_order_amount
    unless @order.lesson.present?
      costs = Amountcalculation.new(@order).calculate_amount(@order, current_user)
      @order.update(amount: costs[:total], port: costs[:port], weight: costs[:weight])
      params[:order] ? @promo = Promo.where(code: params[:order][:promo]).first : @promo = nil
      if @promo
        @order.update(amount: @order.amount * (1 - @promo.percentage), port: @order.port * (1 - @promo.percentage), promo: @promo)
      end
    end
  end

  def document_order_basketlines
    @order.basketlines.each do |basketline|
      @order.promo.present? ? order_discount = @order.promo.percentage : order_discount = 0
      if basketline.ceramique
        basketline.ceramique.offer ? ceramique_discount = basketline.ceramique.offer.discount : ceramique_discount = 0

        basketline.update(
          ceramique_name: basketline.ceramique.name,
          ceramique_qty: basketline.quantity,
          ceramique_id_on_order: basketline.ceramique.id,
          basketline_price: ((basketline.ceramique.price * (1 - ceramique_discount)) * basketline.quantity * (1 - order_discount))
          )
      end
    end
  end

end

app/views/payments/new.html.erb
<% content_for(:title_tag) do %>
  <%= t(:payment)%>
<% end %>

<h1 class="<%=@payment_theme%>-payment-h1"><%= t(:payment)%></h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">

      <div class="pay-form-<%=@payment_theme%>">
        <% unless @order.lesson.present? %>
          <div class="adress text-center">
            <% unless  @order.take_away %>

              <h3><%=t(:delivery)%></h3>
              <h4><%=t(:delivery_lead_time, lead_time: @admin.tracking)%></h4>
              <h4><%= current_user.first_name%> <%= current_user.last_name%></h4>
              <h4><%= current_user.adress%></h4>
              <h4><%= current_user.zip_code%> - <%= current_user.city%></h4>
              <% full_country = ISO3166::Country[current_user.country] %>
              <h4><%= full_country.translations[I18n.locale.to_s] || full_country.name%></h4>
              <% unless @order.lesson.present? %>
                <%= link_to edit_user_registration_path do %>
                  <div class="hidden-xs laptop-link-coord">
                    <%= t(:contact_update)%>
                  </div>
                  <div class="hidden-sm hidden-md hidden-lg mobile-link-coord">
                    <%= t(:contact_update_mobile)%>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <h3><%=t(:order_recover)%></h3>
              <h4><%=t(:order_recover_appointment, name: "#{ENV['FIRSTNAME'].capitalize} #{ENV['LASTNAME'].capitalize}")%></h5>
            <% end %>
          </div>
        <% end %>
        <div class="product-amount lesson-amount text-center">
          <% if @order.lesson.present?  %>
            <h3><%=t(:deposit)%> <%= humanized_money(@order.amount) %> <%= currency_symbol %></h3>
            <h4><%=t(:course)%> <%= @order.lesson.duration%> jours, <%= @order.lesson.student%> <%=t(:person, count: @order.lesson.student)%>.</h4>
            <h4><%=t(:lesson_start)%> <%= @order.lesson.start.day%>/<%= @order.lesson.start.month%>/<%= @order.lesson.start.year%></h4>
          <% else %>
            <% @order.promo ? discount = @order.promo.percentage : discount = 0 %>
            <h3><%=t(:total_amount)%> : <%= @order.take_away ? humanized_money(@order.amount) : humanized_money((@order.amount + @order.port)) %> <%= currency_symbol %></h3>
            <h4><%=t(:total_articles)%> : <%= humanized_money(@order.amount) %> €</h4>
            <% unless @order.take_away %>
              <h4><%=t(:total_port)%> : <%= humanized_money(@order.port) %> €</h4>
            <% end %>
          <% end %>
          <h3 class="payment-choice"><%=t(:stripe_paypal)%></h3>
          <div class="payment-methods">
            <%= form_tag order_payments_path(@order) do %>
              <%= hidden_field_tag "method", "stripe" %>
              <button type="submit" id="stripe-pay" class="pay-button">
                <span><%=t(:pay_by_card)%></span>
              </button>

              <div class="secure">
                <% @payment_theme == "darktheme" ? logo = "stripe.svg" : logo = "stripe-black.svg" %>
                <div class="stripe"><span><%=t(:secured_payment)%></span> <%= image_tag logo, class: "stripe-logo"%></div>
                <p><%=t(:cards)%></p>
                <div class="cards">
                   <%= image_tag "mastercard.svg", class: "mastercard"%> <%= image_tag "visa.svg", class: "visa"%> <%= image_tag "american-express.svg", class: "american-express"%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

  <div id="stripe-errors" class="alert alert-dismissible alert-default" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>

<% content_for(:after_js) do %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= Rails.configuration.stripe[:publishable_key] %>");

    document.getElementById("stripe-pay").addEventListener('click', payWithStripe, false);

    function payWithStripe(event) {
      event.preventDefault();
      stripe.redirectToCheckout({
        sessionId: "<%= @stripe_session %>"
      }).then(function (result) {
        if (result.error.message) {
          var warningDiv = document.getElementById("stripe-errors");
          warningDiv.innerHTML += result.error.message;
          warningDiv.classList.add("active")
        }
        // If `redirectToCheckout` fails due to a browser or network
        // error, display the localized error message to your customer
        // using `result.error.message`.
      });
    }
  </script>
<% end %>

app/views/payments/new_lighttheme.html.erb
<% content_for(:title_tag) do %>
  Paiement
<% end %>

<h1 class="lighttheme-payment-h1">Paiement</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">

      <div class="pay-form-lighttheme">
          <% unless @order.lesson.present? %>
            <div class="adress text-center">
              <h3>Livraison du colis</h3>
              <h4>Livraison via colissimo, sous <%= @admin.tracking%>, à l'adresse suivante:</h5>
              <h4><%= current_user.first_name%> <%= current_user.last_name%></h4>
              <h4><%= current_user.adress%></h4>
              <h4><%= current_user.zip_code%> - <%= current_user.city%></h4>
              <% unless @order.lesson.present? %>
                <%= link_to edit_user_registration_path do %>
                  <div class="btn btn-primary">
                    METTRE A JOUR VOS COORDONNEES
                  </div>
              <% end %>
              <% end %>
            </div>
          <% end %>
          <div class="product-amount lesson-amount text-center">
            <% if @order.lesson.present?  %>
              <h3>Montant des arrhes: <%= humanized_money(@order.amount) %> <%= currency_symbol %></h3>
              <h4>Stage de poterie pour <%= @order.lesson.duration%> jours, <%= @order.lesson.student%> personnes.</h4>
              <h4>Début du stage le <%= @order.lesson.start.day%>/<%= @order.lesson.start.month%>/<%= @order.lesson.start.year%></h4>
            <% else %>
              <h3>Total à payer: <%= humanized_money(@order.amount) %> <%= currency_symbol %></h3>
            <% end %>
            <%= form_tag order_payments_path(@order) do %>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="<%=ENV['MODEL'].capitalize%>"
              data-email="<%= current_user.email %>"

              data-description="<%=ENV['FIRSTNAME'].capitalize%> <%=ENV['LASTNAME'].capitalize%>"
              data-amount="<%= @order.amount_cents %>"
              data-currency="<%= @order.amount.currency %>">
            </script>
            <div class="secure">
              <div class="stripe"><span>Paiement sécurisé par</span> <%= image_tag "stripe-black.svg", class: "stripe-logo"%></div>
              <p>Cartes acceptées</p>
              <div class="cards">
                 <%= image_tag "mastercard.svg", class: "mastercard"%> <%= image_tag "visa.svg", class: "visa"%> <%= image_tag "american-express.svg", class: "american-express"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>